### ISSUE TITLE
1.1.0中假名は与ば依然错位

### ISSUE THREAD

**Issue by onichan0923** [atelier-anchor/smiley-sans#101]
![Screenshot_2023-01-06-22-20-17-00_c6d2f5838c1fca5283099d09ba458d93](https://user-images.githubusercontent.com/68043613/211030589-7f860e2e-b2ee-4bd8-83c9-fd0f33eac237.jpg)
![Screenshot_2023-01-06-22-20-18-80_c6d2f5838c1fca5283099d09ba458d93](https://user-images.githubusercontent.com/68043613/211030600-55d2ffba-96f6-4534-a988-0b75de60cca8.jpg)
如图

**Comment by Skr-ZERO** [comment]
藩也没有改正
