### ISSUE TITLE
关于字体保留名称 About Reserved Font Name

### ISSUE THREAD

**Issue by NightFurySL2001** [atelier-anchor/smiley-sans#105]
请问本字体有字型保留名称（Reserved Font Names/RFN）吗？根据 [字体的授权 LICENSE 文件](https://github.com/atelier-anchor/smiley-sans/blob/main/LICENSE)，本字型并没有宣称任何RFN，但是根据 [oooooohmygosh 于 Bilibili 所发布的声明](https://t.bilibili.com/732500406159015976) 表示衍生字型名称不可以使用“得意黑”一词。

如果本字型已确认禁止衍生字型使用“得意黑”一词，请依据 [OFL 格式](https://scripts.sil.org/ofl) 在 LICENSE 内补上 RFN 宣称（如下）：

> Copyright (c) <dates>, <Copyright Holder> (<URL|email>),
> with Reserved Font Name <Reserved Font Name>.

若没有禁止名称使用，希望 oooooohmygosh 能够出面澄清 bilibili 上面的这段误导性言论：“请不要使用「XX得意黑」这样的命名哦。这是违反OFL开源协议的”。注意该文所引用的 OFL 授权 PERMISSION & CONDITIONS 第 3 段只限 LICENSE 文件内宣称的 RFN 而已，若没有 RFN 声明衍生字体作者是可以使用“得意黑”一词的（包括命名成「XX得意黑」）。谢谢。

---

May I ask if there is Reserved Font Names (RFN) for this font? According to the [LICENSE file](https://github.com/atelier-anchor/smiley-sans/blob/main/LICENSE) this font did not declared any RFNs, but according to the [statement released by ooooohmygosh on bilibili](https://t.bilibili.com/732500406159015976), all Modified fonts should not use the name “得意黑”.

If the font is confirmed to stop all Modified fonts from using the name “得意黑”, please include a RFN declaration in the LICENSE file according to the  [OFL format](https://scripts.sil.org/ofl) (as below):

> Copyright (c) <dates>, <Copyright Holder> (<URL|email>),
> with Reserved Font Name <Reserved Font Name>.

If there is no limitation on using the font name, I would hope for oooooohmygosh to release a clarification on misleading information on bilibili: “请不要使用「XX得意黑」这样的命名哦。这是违反OFL开源协议的” (rough translation: “please everyone don't use naming such as ‘XX得意黑’. This is violating the OFL open source license”). Note that the 3rd paragraph in the OFL license PERMISSION & CONDITIONS section referenced in the post is only limited to the RFNs declaraed in the LICENSE file, if there is no RFN declaration, all Modified font authors are allowed to use the name “得意黑” (including names such as “XX得意黑”). Thank you.

---

bilibili 文章截图 post screenshot:
![Original post on bilibili by oooooohmygosh on 2022-11-25](https://user-images.githubusercontent.com/33471049/212340562-dceddb17-b355-44a6-ab59-221d4eafb2c5.png)

Transcription:
> 大家在得意黑字体基础上进行设计和分发的时候，请不要使用「XX得意黑」这样的命名哦。这是违反OFL开源协议的，因为会让人误以为XX才是得意黑的真正作者。更重要的是，这还会让人误以为我们会为「改动后的」字体设计和工程质量负责。
>
> 在各平台上架的得意黑只会叫「得意黑」三个字，或是加上英文名Smiley Sans，比如必剪。这是我和锚坞兄弟姐妹们付出了大量时间创作的结果，不希望造成不必要的困扰。
>
> 最后感谢众多反馈此问题的观众们，我们目前不会指出已经像这样违反开源协议的人，也暂时不会追责，但是希望尽快修正啦！
> ![Attached image in post](https://user-images.githubusercontent.com/33471049/212342567-3eedffb9-6fe6-4a67-aa59-8e4c467b82c4.png)

**Comment by stone-zeng** [comment]
您好，

感谢您指出关于字体保留名称的问题，抱歉让您产生了困扰。

在撰写 OFL 协议时，我们并未留意到 OFL 格式中需使用特定格式声明 RFN ，而误以为字体的 RFN 是随协议发布而默认的。

这确实是我们的疏漏。按照您的建议，我们已经更新了得意黑的 OFL 协议，敬请查看。鉴于 RFN 在文种上并为制定明显规则，我们将「Smiley」以及「得意黑」都列入了本协议的 RFN。

如果使用者或开发者需对字体进行子集化使用或出于任何原因有意保留得意黑的 RFN，可以联系我们沟通取得相应授权。
