### ISSUE TITLE
字库范围扩大建议

### ISSUE THREAD

**Issue by yanboishere** [atelier-anchor/smiley-sans#111]
何不直接支持《通用规范汉字表》8105 字，而非 GB2312？后者包含了什么字更像是一拍脑门的产物，而前者显然是更具现实意义及考量的。

_Originally posted by @liangjiancang in https://github.com/atelier-anchor/smiley-sans/issues/73#issuecomment-1407646145_

**Comment by lxgw** [comment]
GB/T 2312-1980 由于推行已久，虽然已经转为推荐性标准，但早有广泛的群众基础，现在多数简体中文字体都是基于这个标准所收录的 6763 个汉字制作的。《通用规范汉字表》是 2013 年正式颁布的，收录了 8105 个字，与 GB/T 2312 相比，少了 125 个字（包括低频字、异体字、偏旁部首等，也有一些仍然常用但通规未收的字，后面会提到），多了 1467 个字，多出的字里面有数百字是扩展区汉字，一般的输入法输入起来可能会有些困难。

（GB/T 2312 缺少「啰」「瞭」，可能与这个标准颁布的时间背景有关，当时推行的 1977 年版《简化字总表（第二版）》中将「囉」简化为「罗」、「瞭」简化为「了」（且没有例外注释），1986 年重新修订的《简化字总表》恢复了「啰」「瞭（瞭望义）」二字，比 GB/T 2312 的颁布晚了几年。）

GB/T 2312 收录的一些较常用的字《通用规范汉字表》没有收录，比如牛磺酸的「磺」、隧道施工中一榀钢架间距的「榀」等，而这几个字在通规表内又没有替代字。另外鉴于 GB/T 2312 的广泛推行，通规收录的一些字的规范写法不见得更常用，如鲇鱼的「鲇（鲶）」，「鲇」字 GB/T 2312 和通规表均有收录，而「鲶」字只见于 GB/T 2312，但是后者更常见；同理还有「欸」「诶」，前者收录于通规表，后者收录于 GB/T 2312，但更常见的也是后者。

**Comment by lxgw** [comment]
我把我在 #73 里的评论发到这里吧。

GB/T 2312-1980 由于推行已久，虽然已经转为推荐性标准，但早有广泛的群众基础，现在多数简体中文字体都是基于这个标准所收录的 6763 个汉字制作的。《通用规范汉字表》是 2013 年正式颁布的，收录了 8105 个字，与 GB/T 2312 相比，少了 125 个字（包括低频字、异体字、偏旁部首等，也有一些仍然常用但通规未收的字，后面会提到），多了 1467 个字，多出的字里面有数百字是扩展区汉字，一般的输入法输入起来可能会有些困难。

（GB/T 2312 缺少「啰」「瞭」，可能与这个标准颁布的时间背景有关，当时推行的 1977 年版《简化字总表（第二版）》中将「囉」简化为「罗」、「瞭」简化为「了」（且没有例外注释），1986 年重新修订的《简化字总表》恢复了「啰」「瞭（瞭望义）」二字，比 GB/T 2312 的颁布晚了几年。）

GB/T 2312 收录的一些较常用的字《通用规范汉字表》没有收录，比如牛磺酸的「磺」、隧道施工中一榀钢架间距的「榀」等，而这些字在通规表内又没有替代字。另外鉴于 GB/T 2312 的广泛推行，通规收录的一些字的规范写法不见得更常用，如鲇鱼的「鲇（鲶）」，「鲇」字 GB/T 2312 和通规表均有收录，而「鲶」字只见于 GB/T 2312，但是后者更常见；同理还有「欸」「诶」，前者收录于通规表，后者收录于 GB/T 2312，但更常见的也是后者。

**Comment by yanboishere** [comment]
我觉得未来如果字体团队有时间和精力的话可以考虑一下 👌

**Comment by Skr-ZERO** [comment]
建议再加上“朘塃揾葓湨塈塮蹓檵礳耲”11字，完成《现代汉语通用字表》。

**Comment by aaron2wh** [comment]
期待能夠加入對繁體字型的支援。
謝謝！

**Comment by zwtwz** [comment]
没有梼杌的“梼”字，的确希望扩大字库范围，如果有精力请考虑一下谢谢。
