### ISSUE TITLE
在自己的开源项目中使用得意黑是否需要申请授权

### ISSUE THREAD

**Issue by woshishabii** [atelier-anchor/smiley-sans#116]
### Discussed in https://github.com/atelier-anchor/smiley-sans/discussions/115

<div type='discussions-op-text'>

<sup>Originally posted by **woshishabii** February 18, 2023</sup>
在给班里整一个每日一言，想使用得以黑作为字体，不知道是否需要申请授权
以及得意黑应该以什么形式出现在项目中（ttf文件作为项目一部分还是在actions中下载）</div>

**Comment by stone-zeng** [comment]
并不需要，具体请看 [LICENSE](https://github.com/atelier-anchor/smiley-sans/blob/main/LICENSE)。
