### ISSUE TITLE
对于数学符号，是不是漏了啊

### ISSUE THREAD

**Issue by haoxiaoyueh** [atelier-anchor/smiley-sans#120]
对于圆周率π，我这边显示的是一种类似于”Π“这样的东西，希望能够被改正
![π](https://user-images.githubusercontent.com/113106402/223612593-8f4ed1fc-51f8-407d-afc6-39669160853a.png)

**Comment by Skr-ZERO** [comment]
你是不是还在用1.0.0版本？请到Release界面下载最新版，最新版已经适配了希腊字母。

**Comment by haoxiaoyueh** [comment]
问题解决了，非常感谢
