### ISSUE TITLE
最近是否有更新计划？

### ISSUE THREAD

**Issue by pkj-l** [atelier-anchor/smiley-sans#128]
感谢制作这套字体！
最近是否有更新计划？

**Comment by stone-zeng** [comment]
我们的设计师一直在持续修改，预计今年下半年（10、11 月左右）会有一次集中更新。

**Comment by eleveyuan** [comment]
11月下旬了，等更新ing。想询问下有具体更新内容的列表么 👍

**Comment by stone-zeng** [comment]
目前初步的计划是更新通规 level 2 和 #73 中的补字请求。

**Comment by Skr-ZERO** [comment]
催更~(๑Ő௰Ő๑)
