### ISSUE TITLE
会考虑移除 Reserved Font Name 吗？

### ISSUE THREAD

**Issue by howlingFounts** [atelier-anchor/smiley-sans#149]
您好！[Google Fonts](https://fonts.google.com/) 打算上架得意黑，最近其 Contributor 建议[移除 Reserved Font Name](https://github.com/google/fonts/issues/5550#issuecomment-2458486087)：

> Hi there. The OFL license file in the repository states `with Reserved Font Name <Smiley> and <得意黑>.`. Our preference is no RFN, per the submission guidelines.

Google Fonts 的[手册](https://googlefonts.github.io/gf-guide/onboarding.html)里也提到：

> The Open Font License should not have any Reserved Font Names.

因为 Google Fonts 上架字体时，会把字体分割成很多 woff2 文件，Google 认为包含 Reserved Font Name 的字体[如果做成 webfont，则必须对字体重命名](https://github.com/simoncozens/silson/issues/1)。

会考虑移除 Reserved Font Name 吗？多谢！

**Comment by stone-zeng** [comment]
See #105.
