### ISSUE TITLE
请求添加“昐”字

### ISSUE THREAD

**Issue by LvJiarunNuaa** [atelier-anchor/smiley-sans#19]
请求添加日字旁的“昐”字

**Comment by lxgw** [comment]
这个字 GB/T 2312 和通规表都没有收录，倒是古籍字表收录了。

![image](https://user-images.githubusercontent.com/51902309/202061279-496bbb26-87fe-4dc2-83bc-fff0e7a7d252.png)

**Comment by StringKe** [comment]
@lxgw 请问这个查询工具是什么

**Comment by lxgw** [comment]
> @lxgw 请问这个查询工具是什么

[字统网](http://zi.tools)
