### ISSUE TITLE
「は (U+306F)」「ば (U+3070)」的字形错位

### ISSUE THREAD

**Issue by blueset** [atelier-anchor/smiley-sans#2]
「は (U+306F)」「ば (U+3070)」的实际显示字形被交换，如图。

应显示「はば」实际显示的是「ばは」。

<img width="440" alt="image" src="https://user-images.githubusercontent.com/553831/201821912-35ab7449-dfa9-46ca-ad30-8a07c58ff1a5.png">

**Comment by zhangjiuyun** [comment]
同发现这两个反了

**Comment by zhangjiuyun** [comment]
![スクリーンショット 2022-11-15 192544](https://user-images.githubusercontent.com/50827746/201896068-e931ad6d-6f6b-4cad-8f4b-082c4192da9e.jpg)
在日语里输入日文汉字和假名的时候，斜率会不太自然

**Comment by Buernia** [comment]
> ![スクリーンショット 2022-11-15 192544](https://user-images.githubusercontent.com/50827746/201896068-e931ad6d-6f6b-4cad-8f4b-082c4192da9e.jpg) 在日语里输入日文汉字和假名的时候，斜率会不太自然

这字体没做日文汉字，缺的字回退到了机械倾斜的其他字体。

**Comment by HiRA017** [comment]
> ![スクリーンショット 2022-11-15 192544](https://user-images.githubusercontent.com/50827746/201896068-e931ad6d-6f6b-4cad-8f4b-082c4192da9e.jpg) 在日语里输入日文汉字和假名的时候，斜率会不太自然

目前好像还没有对日文汉字以及任一标准（陆台港）的繁体字做适配，字体 fallback 了
