### ISSUE TITLE
好像不太适合写代码用。哈哈哈哈

### ISSUE THREAD

**Issue by sunshineLixun** [atelier-anchor/smiley-sans#20]
![image](https://user-images.githubusercontent.com/15700015/202062179-8da3bc76-e3d2-4aed-97b2-3e6dcf6e9b42.png)

**Comment by Rinkaa** [comment]
Duplicate of #13

**Comment by YtotheWT** [comment]
> ![image](https://user-images.githubusercontent.com/15700015/202062179-8da3bc76-e3d2-4aed-97b2-3e6dcf6e9b42.png)
> 

你拿指甲刀削水果？这个字体本来就不是专门为写代码设计的，用作IDE字体当然不合适

**Comment by didikee** [comment]
写代码使用等宽字体可能比较好。这是艺术字体的特点是 窄和斜，可以作为平时做一些海报和宣传画时使用。

**Comment by stone-zeng** [comment]
Duplicate of #13.
