### ISSUE TITLE
为啥我的idea导入之后是这样子？哈哈。

### ISSUE THREAD

**Issue by duocoding** [atelier-anchor/smiley-sans#24]
![481668567528_ pic](https://user-images.githubusercontent.com/48700579/202072823-80520f97-3f35-49e9-b6e7-24ae06690601.jpg)

**Comment by YtotheWT** [comment]
我想问一下你为什么要把这样一个艺术字体导入IDEA

**Comment by shenjackyuanjie** [comment]
> 我想问一下你为什么要把这样一个艺术字体导入IDEA

闲的呗，想看看效果嘛
哈哈哈哈

**Comment by duocoding** [comment]
打工之余找点乐趣，码农不配艺术点吗，哈哈哈😂

**Comment by blackcater** [comment]
编程还是要用 Mono 字体啊。这个不适合当做编程字体
编程还是推荐使用 Jetbrains Mono, Cascadia Mono, Firacode Mono
中文的可以使用华为的 HarmonyOS Sans

或者你可以使用一款斜体的 Mono 字体作为主字体，再使用得意黑作为 fallback 字体。

**Comment by duocoding** [comment]
> 编程还是要用 Mono 字体啊。这个不适合当做编程字体 编程还是推荐使用 Jetbrains Mono, Cascadia Mono, Firacode Mono 中文的可以使用华为的 HarmonyOS Sans
> 
> 或者你可以使用一款斜体的 Mono 字体作为主字体，再使用得意黑作为 fallback 字体。

好的，谢谢大佬 !salute
