### ISSUE TITLE
“港” 的字形问题

### ISSUE THREAD

**Issue by Buernia** [atelier-anchor/smiley-sans#25]
注意下图画圈的部分，两竖超出了横画，露出了尖角。

<img width="662" alt="截屏2022-11-16 12 07 26" src="https://user-images.githubusercontent.com/11886946/202081218-7a740b96-de7f-4098-a4de-22351b2833f6.png">

**Comment by stone-zeng** [comment]
Fixed in de9a1aa14961b2ff80ecd2119926ba72207653b1.
