### ISSUE TITLE
有无计划开发基于得意黑设计风格的等宽英文字体？

### ISSUE THREAD

**Issue by xkgeng** [atelier-anchor/smiley-sans#26]
因为我写代码很喜欢用斜体，但现有的斜体看着都太斜了，没有得意黑那样舒服，期待基于得意黑设计风格的等宽英文字体~

**Comment by YtotheWT** [comment]
推荐JetBrains Mono，斜体的斜率只有9°，正合适😉

**Comment by stone-zeng** [comment]
Duplicate of #13.
