### ISSUE TITLE
大写字母“O”和数字“0”不好辨识，大写的“i”和小写的"L"也不好辨识

### ISSUE THREAD

**Issue by JF18** [atelier-anchor/smiley-sans#28]
大写字母“O”和数字“0”不好辨识，大写的“i”和小写的"L"也不好辨识

**Comment by KaoYUG** [comment]
"O"可以做粗一些。
i和L已经有人反映过了，不要重复反映

**Comment by JF18** [comment]
> "O"可以做粗一些。 i和L已经有人反映过了，不要重复反映

issues中没看见有反馈，我也不知道是重复反馈呢

**Comment by chrisOne1** [comment]
#12 的副本。你可以关闭此issue，最好保持在一个issue中集中讨论。

**Comment by JF18** [comment]
https://github.com/atelier-anchor/smiley-sans/issues/12
