### ISSUE TITLE
未来计划

### ISSUE THREAD

**Issue by Skr-ZERO** [atelier-anchor/smiley-sans#3]
非常不错的字体，感谢团队的辛苦付出！请问这款字体未来还有做更多汉字的打算吗？比如补完《通用规范汉字表》或增加繁体字。

**Comment by stone-zeng** [comment]
会有的，而且也有增加正体、粗体等的计划。

**Comment by BobH-Official** [comment]
您好，我发现得意黑本身就属于比较“粗”的字体，所以请问是否有考虑出细一点的字体呢（比如说适合较小字号的变体）？ @stone-zeng

**Comment by BobH-Official** [comment]
另外，有考虑出”等宽“版本吗？

**Comment by weirick** [comment]
记得加上日语汉字

**Comment by ItMarki** [comment]
请问有计划做注音符号吗？

**Comment by xzpeter** [comment]
同求等宽字体。国内外有大量的软件工程师，如果有了等宽字体可能会增加大量的受众。编程中主要是非中文字符。无论如何，很期待字体的进一步发展。

**Comment by Jinxiansen** [comment]
+1
