### ISSUE TITLE
请求适配“垚”和“壵”

### ISSUE THREAD

**Issue by lowy** [atelier-anchor/smiley-sans#32]
![2022-11-16-21-16-50](https://user-images.githubusercontent.com/6565177/202192441-27a7a3ec-2e48-4c9b-8763-e7fc2b8747c9.png)

**Comment by lxgw** [comment]
垚：

![image](https://user-images.githubusercontent.com/51902309/202607827-edfce583-75b4-4e5d-b076-3608227be948.png)

壵：

![image](https://user-images.githubusercontent.com/51902309/202607858-ceccdabc-dfa1-43b7-890f-6138dd466660.png)

「垚」字在《通用规范汉字表》，是三级字；「壵」字比较生僻，是「壮」的异体。
