### ISSUE TITLE
愛字未适配

### ISSUE THREAD

**Issue by shenjackyuanjie** [atelier-anchor/smiley-sans#33]
![image](https://user-images.githubusercontent.com/54507071/202209172-f02df340-14d1-42d9-b2fa-854e8e10adda.png)
（打我的名字的相近字的碰到的，还是蛮生僻的

**Comment by TimeSheepY** [comment]
这是繁体“愛”，简体是“爱”，是缺少繁体的原因

**Comment by shenjackyuanjie** [comment]
OK
（适配了瑗还是很惊讶的（虽说不应该惊讶吧
Thanks♪(･ω･)ﾉ

**Comment by lxgw** [comment]
> OK （适配了瑗还是很惊讶的（虽说不应该惊讶吧 Thanks♪(･ω･)ﾉ

因为「瑗」是 GB/T 2312 里收录的字（下图中 G0 代表 GB/T 2312）
![image](https://user-images.githubusercontent.com/51902309/202468472-0ab8ab0d-3ec6-4647-ae48-c2b07f1e4e73.png)

**Comment by shenjackyuanjie** [comment]
> > OK （适配了瑗还是很惊讶的（虽说不应该惊讶吧 Thanks♪(･ω･)ﾉ
> 
> 因为「瑗」是 GB/T 2312 里收录的字（下图中 G0 代表 GB/T 2312） ![image](https://user-images.githubusercontent.com/51902309/202468472-0ab8ab0d-3ec6-4647-ae48-c2b07f1e4e73.png)

知道哒，谢谢！Thanks♪(･ω･)ﾉ
