### ISSUE TITLE
希望照顾下windows用户。

### ISSUE THREAD

**Issue by zouchengjun** [atelier-anchor/smiley-sans#35]
glyph是mac独占软件。希望能导出fontlab或者fontcreator、fontforge支持的中间文件

**Comment by stone-zeng** [comment]
为了不增大 git repo 的体积，所以没有把中间文件存进来。需要的话，可以使用 [fontmake](https://github.com/googlefonts/fontmake) 或者 [glyphsLib](https://github.com/googlefonts/glyphsLib) 等把源文件导出为 ufo 格式。
