### ISSUE TITLE
得意黑很好看，发现两个字没适配(棨，襜）

### ISSUE THREAD

**Issue by zhkgo** [atelier-anchor/smiley-sans#36]
![image](https://user-images.githubusercontent.com/39695505/202337121-308e4612-b336-4d48-8aa5-edd4c8c0ee32.png)

**Comment by TimeSheepY** [comment]
不属于GB2312-80，等官方后续增加字体吧

**Comment by lxgw** [comment]
棨、襜、𬴂 都是《通用规范汉字表》收录的字，等官方后续的计划吧。

**Comment by TPAXcc** [comment]
适配范围需要一点一点来
