### ISSUE TITLE
请求适配“旻”字

### ISSUE THREAD

**Issue by Surfire** [atelier-anchor/smiley-sans#37]

**Comment by TimeSheepY** [comment]
![image](https://user-images.githubusercontent.com/59170247/202347218-88d7392c-b524-4588-a092-d4e0b5ddd129.png)

**Comment by lxgw** [comment]
GB/T 2312 没有「旻」这个字，儋《通用规范汉字表》有。看官方后续的计划吧，需要一点一点来。

**Comment by leveychen** [comment]
这个只能慢慢来了，毕竟异体字二级三级字一大堆，我那天下载了放游戏里一看，全是口口口，等各位大佬慢慢优化吧
