### ISSUE TITLE
字体 祇 的缺失

### ISSUE THREAD

**Issue by yuelsun** [atelier-anchor/smiley-sans#44]
![image](https://user-images.githubusercontent.com/78309576/202605054-d89deb5f-9052-4533-a90f-bab66b1fbf11.png)

**Comment by lxgw** [comment]
![image](https://user-images.githubusercontent.com/51902309/202606843-1b361a6e-05fd-448f-8f28-1d4c7d2474ad.png)

GB/T 2312 没有「神祇」的「祇」这个字，但通用规范汉字表有。看官方后续的计划吧，需要一点一点来。
