### ISSUE TITLE
Issues整理、清理建议

### ISSUE THREAD

**Issue by scillidan** [atelier-anchor/smiley-sans#46]
个人认为`issues`不适合放「单个字添加」、「缺字」等此类请求，对仓库的整体信息量有影响。影响查看`issue`时的信息密度，而管理和统计`issues`都要花时间，这类数据统计后，销毁比保存更值得。

建议关闭相关请求，并在`README`增加“待更新”内容，提示或包含这类内容。
建议尝试一种有示范意义的「提交」、「统计」、「整合公布」的流程。

**Comment by lxgw** [comment]
可以单独开一个提交缺字或改字专用 Issue，让大家提交缺字或错形的时候统一到专门的 Issue 里回复，而不是另开 Issue。

类似这样：
![image](https://user-images.githubusercontent.com/51902309/202632965-44695443-0e7a-4ad0-a727-37ad1e4ffdff.png)
![image](https://user-images.githubusercontent.com/51902309/202632993-86334083-00da-41cb-9a3f-351f9879383b.png)

**Comment by scillidan** [comment]
对对对，是这种。

类似这样：https://github.com/ocornut/imgui/issues/5243

**Comment by stone-zeng** [comment]
See #73.
