### ISSUE TITLE
如何将安卓手机系统的字体更换为得意黑？

### ISSUE THREAD

**Issue by f2sky** [atelier-anchor/smiley-sans#5]
系统设置里面没有找到更换自定义字体的选项。有如下疑问：
1、是否需要 root ？该如何替换字体？
2、为避免发生手机死机、无法启动、乱码显示等意外，有哪些需要注意的？

**Comment by Kimaindono** [comment]
这种问题请自行去搜索引擎上寻找相关内容

**Comment by YtotheWT** [comment]
> 系统设置里面没有找到更换自定义字体的选项。有如下疑问： 1、是否需要 root ？该如何替换字体？ 2、为避免发生手机死机、无法启动、乱码显示等意外，有哪些需要注意的？

不同牌子的手机要求不一样

**Comment by xzy-nine** [comment]
https://www.coolapk.com/feed/41024836?shareKey=ODgzZWZiM2JlZTE0NjM3Mzk0ZWQ~&shareUid=3789833&shareFrom=com.coolapk.market_12.5.2
已经有人制作了模块,有经验的可以尝试刷入

**Comment by qyd0801** [comment]
不建议把艺术字作为系统默认字体。。
