### ISSUE TITLE
请支持西里尔字母（俄语）

### ISSUE THREAD

**Issue by lccggg** [atelier-anchor/smiley-sans#55]
你这字体不支持俄语字母，word上输入西里尔字母后无法换成得意黑，其他地方则是直接变宋体或微软雅黑（不确定是不是）。
西里尔字母：https://baike.sogou.com/v424448.htm?fromTitle=%E8%A5%BF%E9%87%8C%E5%B0%94%E5%AD%97%E6%AF%8D#!

**Comment by lccggg** [comment]
![Snipaste_2022-11-20_10-40-32](https://user-images.githubusercontent.com/79234156/202888388-4edd6bfa-937a-4e67-b0cb-5369f9cf8e59.png)
上面是得意黑，下面是等线

**Comment by stone-zeng** [comment]
Duplicate of #17.
