### ISSUE TITLE
得意黑字体都是斜体，导致某些软件图标也变斜了

### ISSUE THREAD

**Issue by SZ2528** [atelier-anchor/smiley-sans#64]
RT
![image](https://user-images.githubusercontent.com/83620631/202967835-b82c6be1-130c-4357-afe1-6d8095c3da1d.png)

**Comment by mxr612** [comment]
因为图标是Unicode里面的吗？这叫特性理解一下（笑）

**Comment by CAPCOMIN** [comment]
不建议将美术字用作系统正文字体

**Comment by ACh-K** [comment]
> RT ![image](https://user-images.githubusercontent.com/83620631/202967835-b82c6be1-130c-4357-afe1-6d8095c3da1d.png)

是說有點好奇這是不是直接直接改系統的字體，因為圖中的是 PowerToys 裡的 PowerToys Run，然後照理來說 PowerToys 會直接挪用系統的字體🤔
<img width="720" alt="image" src="https://user-images.githubusercontent.com/98224334/204697199-790734e8-b70c-4c85-8500-bfb56e6d1164.png">
