### ISSUE TITLE
[请求添加等宽字体版本]：期望"得意黑"能朝编程字体发展

### ISSUE THREAD

**Issue by Mango-Golden** [atelier-anchor/smiley-sans#65]
* 描述: 好像目前现有的中文字体都和英文字体不等宽, 得意黑会考虑做等宽版本吗?(话说有谁能教一下我怎么看字宽吗)
<img width="662" alt="image" src="https://user-images.githubusercontent.com/54613568/202946363-62e2518d-8c4f-45d9-9d35-b4fab6fbc3e3.png">

* 环境说明
1. MacOs Monterey 12.6
2. VSCode 1.73.1 

* 期望: 提供和 `Fira Code`, `Cascadia Code` 等编程字体等宽的字体版本。

**Comment by stone-zeng** [comment]
> 话说有谁能教一下我怎么看字宽吗

得意黑的中文字宽是 800（全宽 1000），西文是比例宽度的。

**Comment by stone-zeng** [comment]
Duplicate of #13.
