### ISSUE TITLE
[欸]字尚未适配

### ISSUE THREAD

**Issue by Dongyifengs** [atelier-anchor/smiley-sans#7]
如题

**Comment by Dongyifengs** [comment]
![mmexport1668508639369.png](https://user-images.githubusercontent.com/62745541/201898770-2c319f22-2891-4efc-bd8a-b0c6e3b04d21.png)

**Comment by lxgw** [comment]
「欸」是通用规范汉字表收录的字，但不见于 GB/T 2312-80，GB 2312 收录的是「诶」。不过官方应该是有补全「通规表」的计划吧。
