### ISSUE TITLE
汉字调整请求整理

### ISSUE THREAD

**Issue by stone-zeng** [atelier-anchor/smiley-sans#74]
本 issue 整理了现在的汉字设计调整、修复请求，如果有其他需要，可以在下面留言。

- [x] `缏` - #23
- [x] `港` - #25
- [x] `冱`
- [x] `贬`
- [x] `l I`
- [ ] ~~`怎`~~
- [ ] ~~`o O 0`~~

**Comment by KS-OTO** [comment]
我不懂字体设计，只是提个建议，作者酌情采纳。
--------------------------------------------
建议优化“怎”的字体表现，其和“么”组合使用时，总有种不协调感——感觉“么”的字形更公正，“怎”反而斜体的更明显；
![1671505870566](https://user-images.githubusercontent.com/6616413/208572695-bb810f42-d4f7-4b00-9299-b1bf072ec150.png)
![微信图片_20221220110830](https://user-images.githubusercontent.com/6616413/208572718-21c76825-228c-463d-b7b2-20af45599e8a.png)

**Comment by AzusaHayashi** [comment]
日语字体中“は”和“ば”的显示有误，两个字正好反过来了。

**Comment by stone-zeng** [comment]
> 日语字体中“は”和“ば”的显示有误，两个字正好反过来了。

Fixed in #2.

**Comment by Skr-ZERO** [comment]
> ![Snipaste_2023-01-10_17-51-58](https://user-images.githubusercontent.com/35125888/211522424-b507cc76-af64-4920-9aa2-3afacd88fa94.png) ![Snipaste_2023-01-10_17-58-22](https://user-images.githubusercontent.com/35125888/211522457-3efc4c5f-0e84-4fda-b897-bbd5f826c9c0.png) 这两个字显示异常，辛苦了！

因为这两个字还没有做，如果有添加汉字的需求，可以到 #73 反馈。

**Comment by yanboishere** [comment]
> ![Snipaste_2023-01-10_17-51-58](https://user-images.githubusercontent.com/35125888/211522424-b507cc76-af64-4920-9aa2-3afacd88fa94.png)
> ![Snipaste_2023-01-10_17-58-22](https://user-images.githubusercontent.com/35125888/211522457-3efc4c5f-0e84-4fda-b897-bbd5f826c9c0.png)
> 这两个字显示异常，辛苦了！

该问题是因为这两个字不在GB/T 2312-1980范围之中，如果你有添加汉字的需求，请到[https://github.com/atelier-anchor/smiley-sans/issues/73](url)

**Comment by yanboishere** [comment]
> ![Snipaste_2023-01-10_17-51-58](https://user-images.githubusercontent.com/35125888/211522424-b507cc76-af64-4920-9aa2-3afacd88fa94.png)
> ![Snipaste_2023-01-10_17-58-22](https://user-images.githubusercontent.com/35125888/211522457-3efc4c5f-0e84-4fda-b897-bbd5f826c9c0.png)
> 这两个字显示异常，辛苦了！

https://github.com/atelier-anchor/smiley-sans/issues/73#issuecomment-1412171093 我已将这两字加入到 #73 中

**Comment by 866837** [comment]
怎么和原版思源字体一样有基线行高的问题。
字体下发空白太多，请求调整，谢谢

**Comment by aaron2wh** [comment]
可以增加繁體漢字的支持，另外如果可以請增加一款正常（非斜體）的字體版本。
非常喜歡得意黑，為作者點讚！

**Comment by JavieDeng** [comment]
想请大佬为得意黑加点小小细节。在识别到：）这个表情的时候能不能让这表情显示的更好看，更得意一些呢？
![image](https://user-images.githubusercontent.com/67130135/228586147-8bf7e36e-6cfb-43f0-afea-e8c7c411f050.png)
现在显示效果如图

**Comment by Usagixineist** [comment]
关于 冱(u51b1) 中 互 部件左下折角多伸出1px的细节问题
![image](https://user-images.githubusercontent.com/118468467/231710819-b502effb-5599-4fae-bf89-a5f72cbf0ced.png)
![image](https://user-images.githubusercontent.com/118468467/231710898-38fcc3a0-4664-4c4c-830d-46022fbb1e5d.png)

**Comment by Skr-ZERO** [comment]
贬![image](https://user-images.githubusercontent.com/62774986/232276663-9577264d-1fed-4492-88bb-4639404fea5b.png)

**Comment by isZio** [comment]
lIoO0 这五个的辨识度太低了，希望能优化一下。
![Snipaste_2023-05-22_14-43-21](https://github.com/atelier-anchor/smiley-sans/assets/90860916/21e3bee4-aee1-4492-a1ff-1840c56f375a)

**Comment by KS-OTO** [comment]
![image](https://github.com/atelier-anchor/smiley-sans/assets/6616413/099aeebc-9308-41c1-9839-a822454f4ca8)
【险】字的双耳旁有点拥挤；
【预警】二字，笔画之前的间隙太小，都要黏在一起了，尤其是【警】字上的苟和下方的言

**Comment by stone-zeng** [comment]
> ![image](https://user-images.githubusercontent.com/6616413/252324712-099aeebc-9308-41c1-9839-a822454f4ca8.png)
> 【险】字的双耳旁有点拥挤；
> 【预警】二字，笔画之前的间隙太小，都要黏在一起了，尤其是【警】字上的苟和下方的言
> ![image](https://user-images.githubusercontent.com/6616413/252325437-34935722-5ae9-4435-98e2-8a659a941735.png)
> ![image](https://user-images.githubusercontent.com/6616413/252325643-b84655c3-382f-4476-9fd7-51cc09c63b2c.png)

看起来是调整过了粗细，正常情况应还是 ok 的：

<img width="441" alt="Screenshot 2023-07-10 at 22 23 45" src="https://github.com/atelier-anchor/smiley-sans/assets/18233088/55e26b16-db2c-48b8-8b63-c8913f6bb782">

**Comment by Skr-ZERO** [comment]
#82

**Comment by jz8-armohb** [comment]
v2.0.1版本中的新增汉字，“頫”似乎没有支持
![202402090948_znUhoK](https://raw.githubusercontent.com/jz8-armohb/image-hosting/main/uPic/202402090948_znUhoK.png)
