### ISSUE TITLE
`藩` 字有误

### ISSUE THREAD

**Issue by stone-zeng** [atelier-anchor/smiley-sans#82]
`藩`（U+85E9）与 `蕃` （U+8543）用了同样的字形：

<img width="609" alt="Screenshot 2022-12-08 at 00 03 04" src="https://user-images.githubusercontent.com/18233088/206229200-f63cecce-df76-4ac3-a1be-377a44bfcd5f.png">

**Comment by Mongkol67** [comment]
> `藩`（U+85E9）与 `蕃` （U+8543）用了同样的字形：
> 
> <img alt="Screenshot 2022-12-08 at 00 03 04" width="609" src="https://user-images.githubusercontent.com/18233088/206229200-f63cecce-df76-4ac3-a1be-377a44bfcd5f.png">
